#!/bin/sh

#tcl eval set radar(Main,vessel,vostok,newy)

name=vostok
x=0
y=500
while true ; do
  echo "tcl eval set radar(Main,vessel,vostok,newx) $x; set radar(Main,vessel,vostok,newy) $y\n" | nc 127.0.0.1 9999
  if [ $y -eq 500 -a $x -lt 500 ] ; then
    x=`expr $x + 10`
  else
    if [ $x -eq 500 -a $y -gt -500 ] ; then
      y=`expr $y - 10`
    fi
  fi
  sleep 0.5
  

done
