#!/bin/sh
#
# Examples - not for use, only for inspiration

gst-launch -v alsasrc ! 'audio/x-raw-int, width=(int)16, depth=(int)16, rate=(int)44100, channels=(int)2, endianness=(int)1234, signed=(boolean)true' ! audioconvert ! $AUDIOFORMAT ! tcpclientsink host=193.88.237.22 port=9102

nc -l 9999 | (head -1 ; gst-launch filesrc location=/dev/fd/0 ! 'audio/x-raw-int, endianness=(int)1234, signed=(boolean)true, width=(int)16, depth=(int)16, rate=(int)44100, channels=(int)2' ! autoaudiosink)

 (echo hej ; gst-launch -q filesrc location=test/LES_TDS_launch.mp4 ! decodebin2 name=decoder ! 'audio/x-raw-int, endianness=(int)1234, signed=(boolean)true, width=(int)16, depth=(int)16, rate=(int)44100, channels=(int)2' ! filesink location=/dev/fd/1) | nc 127.0.0.1 9999

# This example will change a controller connection to an audio write out, if the channel has been
# configured in advance
# The config parameters are :
#	audio sink add 1 Audio Sink #1
#	audio sink channels 1 2
#	audio sink rate 1 44100
#	audio sink format 1 16 signed
#	audio sink mute off 1
#	audio sink source feed 1 4

(echo 'audio sink ctr isaudio 1' ; cat) | nc 127.0.0.1 9999 | (head -1; gst-launch filesrc location=/dev/fd/0 ! 'audio/x-raw-int, endianness=(int)1234, signed=(boolean)true, width=(int)16, depth=(int)16, rate=(int)44100, channels=(int)2' ! audioconvert ! autoaudiosink)^C
pmm@MyVbox:~/Projects/Snowmix-0.3.5/scripts$ 

# This example will read audio sample from a pipe
# The config parameters are :
#	audio sink add 1 Audio Sink #1
#	audio sink channels 1 2
#	audio sink rate 1 44100
#	audio sink format 1 16 signed
#	audio sink mute off 1
#	audio sink source feed 1 4
#	audio sink start 1

while true ; do gst-launch -v filesrc location=../src/pmm.pipe ! 'audio/x-raw-int, endianness=(int)1234, signed=(boolean)true, width=(int)16, depth=(int)16, rate=(int)44100, channels=(int)2' ! audioconvert ! autoaudiosink ; sleep 2 ; done
