#!/bin/bash
# Deliver mixer1 output to screen.

ip=127.0.0.1
port=9999
audio_sink_id=1

rate=`echo audio sink rate | nc $ip $port | grep 'STAT: audio sink '$audio_sink_id' ' | cut -f6 -d' '`
channels=`echo audio sink channels | nc $ip $port | grep 'STAT: audio sink '$audio_sink_id' ' | cut -f6 -d' '`

tmpfile=/tmp/output2screen.tmp.$$
echo 'system info' | nc 127.0.0.1 $port >$tmpfile
geometry=`grep 'STAT:  System geometry' $tmpfile |cut -f3 -d: |cut -f2 -d' '|tr 'x' ' '`
framerate=`grep 'STAT:  Frame rate' $tmpfile |cut -f3 -d: |cut -f2 -d' '`
ctrsocket=`grep 'STAT:  Output ctr socket' $tmpfile |cut -f3 -d: |cut -f2 -d' '`
rm $tmpfile

frameratefraction()
{
  echo $1 | awk '{ rate=$1 ;
         factor=1;
         intrate=int(rate);
         while (factor*rate > intrate) {
           factor = factor * 10;
           intrate = int(rate*factor);
         }
         printf("%d/%d\n",intrate,factor);
       }'
}
ratefraction=`frameratefraction $framerate`
           
width=`echo $geometry |cut -f1 -d' '`
height=`echo $geometry |cut -f2 -d' '`


MIXERFORMAT='video/x-raw-rgb, bpp=(int)32, depth=(int)32, endianness=(int)4321, format=(fourcc)BGRA, red_mask=(int)65280, green_mask=(int)16711680, blue_mask=(int)-16777216, width=(int)'$width', height=(int)'$height', framerate=(fraction)'$ratefraction', pixel-aspect-ratio=(fraction)1/1, interlaced=(boolean)false'
AUDIOFORMAT='audio/x-raw-int, endianness=(int)1234, signed=(boolean)true, width=(int)16, depth=(int)16, rate=(int)'$rate', channels=(int)'$channels

while true ; do
  snowmix=`ps c |cut -c28-34 | grep snowmix | head -1`
  if [ X$snowmix != X ] ; then
    (echo audio sink ctr isaudio 1 ; cat >/dev/null ) | \
      nc 127.0.0.1 9999 | \
    ( head -1
      gst-launch-0.10 -q shmsrc socket-path=$ctrsocket do-timestamp=true is-live=true ! \
        $MIXERFORMAT		! \
        ffmpegcolorspace		! \
        ximagesink		  \
        fdsrc fd=0		! \
        $AUDIOFORMAT		! \
        audioconvert		! \
        audioresample		! \
        autoaudiosink
    )
  else
    echo Snowmix is not running. Quitting $0
    exit 1
  fi
  sleep 2
done
