#!/bin/bash

term=`which gnome-terminal`
if [ X$term = X ] ; then
  echo "gnome-terminal not found."
  term=`which xterm`
  if [ X$term = X ] ; then
    echo "xterm not found. Need a window terminal to run. Exiting"
    exit
  fi
fi

system=`uname -s`
if [ $system != Linux ] ; then
  echo This demo script has been tailored for Linux system only
  echo To use this demo, you will need to edit the demo file for your system
  exit 1
fi

check_packages()
{
  for pkg in tcl8.5 tk8.5 bwidget ; do
    echo Checking for package $pkg
    installed=`dpkg --get-selections $pkg`
    if [ "X$installed" = X ] ; then
      echo "Missing $pkg. You need to install $pkg"
      echo "You can install $pkg by executing the following command"
      echo "  sudo apt-get install $pkg"
      exit 1
    fi
  done
}

get_shm()
{
  shm=`df -k |grep '/run/shm' | awk '{printf("%d\n", $4/1024)}'`
  if [ X$shm = X ] ; then shm=0 ; fi
  if [ $shm -lt $1 ] ; then
    echo 'not enough shared memory. Delete some files in /run/shm/' 1>&2
    exit 1
  fi
  echo $shm
}

select_inifile()
{
  echo "1) tm65-virtual_feeds" >/dev/tty
  echo "2) shape-test" >/dev/tty
  echo "3) sapphire-basis" >/dev/tty
  echo -e "Please select one of the demos (1/2/3/q) : \c" >/dev/tty
  read reply
  if [ X$reply = X1 ] ; then
    echo tm65-virtual_feeds
  else
    if [ X$reply = X2 ] ; then
      echo shape-test
    else
      if [ X$reply = X3 ] ; then
        echo sapphire-basis
      else
        echo "Quitting" >/dev/tty
        echo quit
        exit
      fi
    fi
  fi
}

check_packages
get_shm 20

inifile=`select_inifile`
if [ X$inifile = Xquit ] ; then
  exit
fi

cd ../src
$term -e "./snowmix ../ini/$inifile"&
cd ../scripts
( cd ../tcl
  sleep 2
  ./snowcub.tcl 127.0.0.1 9999 >/dev/null 2>&1
)&

sleep 1
$term -e ./av_output2screen &
sleep 1
(
	#for id in 4 1 2 3 ; do
	#for id in 4 1 2 3 ; do
	for id in 4 1  ; do
          get_shm 20
	  #$term -iconic -e sh input2feed $id&
	  $term -e "sh input2feed $id"&
	  sleep 5
	done
)&
if [ X$inifile = Xshape-test ] ; then
sleep 5
  bash saphire_simulation
fi
