#!/bin/bash
# Deliver mixer1 output to screen.

SRC='shmsrc socket-path=/tmp/mixer1 do-timestamp=true is-live=true'
MIXERFORMAT='video/x-raw-rgb, bpp=(int)32, depth=(int)32, endianness=(int)4321, format=(fourcc)BGRA, red_mask=(int)65280, green_mask=(int)16711680, blue_mask=(int)-16777216, width=(int)1024, height=(int)576, framerate=(fraction)24/1, pixel-aspect-ratio=(fraction)1/1, interlaced=(boolean)false'
X264SETTINGS='bitrate=3000 tune=zerolatency speed-preset=5'
#X264SETTINGS='bitrate=1000 profile=high bframes=2 dct8x8=true tune=zerolatency speed-preset=6'
AUDIOFORMAT='audio/x-raw-int, endianness=(int)1234, signed=(boolean)true, width=(int)16, depth=(int)16, rate=(int)44100, channels=(int)1'

i=0
while true ; do
  file=snowmix-$i.ts
  if [ -s $file ] ; then
    i=`expr $i + 1`
    file=snowmix-$i.mp4
  else
AUDIOFORMAT='audio/x-raw-int, endianness=(int)1234, signed=(boolean)true, width=(int)16, depth=(int)16, rate=(int)44100, channels=(int)1'
MIXERFORMAT='video/x-raw-rgb, bpp=(int)32, depth=(int)32, endianness=(int)4321, format=(fourcc)BGRA, red_mask=(int)65280, green_mask=(int)16711680, blue_mask=(int)-16777216, width=(int)1024, height=(int)576, framerate=(fraction)24/1, pixel-aspect-ratio=(fraction)1/1, interlaced=(boolean)false'
SRC='shmsrc socket-path=/tmp/mixer1 do-timestamp=true is-live=true'

	(echo 'audio sink ctr isaudio 1' ; cat>/dev/null) |  nc 127.0.0.1 9999 | (head -1 ; gst-launch -e mpegtsmux name=muxer ! queue ! tcpserversink port=5010 $SRC ! $MIXERFORMAT ! ffmpegcolorspace ! queue ! x264enc $X264SETTINGS ! h264parse ! queue ! muxer. fdsrc fd=0 ! $AUDIOFORMAT ! lamemp3enc ! queue ! muxer.)
exit
	(echo 'audio sink ctr isaudio 1' ; cat>/dev/null) | \
	nc 127.0.0.1 9999 | \
	(
		head -1
		gst-launch-0.10 -v			  \
			mpegtsmux name=muxer		! \
			queue 				! \
			tcpserversink port=5010		  \
      			$SRC				! \
      			$MIXERFORMAT			! \
      			ffmpegcolorspace		! \
      			queue				! \
      			x264enc $X264SETTINGS		! \
			h264parse			! \
			muxer.				  \
			fdsrc fd=0 do-timestamp=true	! \
			queue				! \
			$AUDIOFORMAT			! \
			lamemp3enc			! \
			queue				! \
			muxer.				  
	)
	


#    gst-launch-0.10 -v              \
#      $SRC                  	  ! \
#      $MIXERFORMAT                ! \
#      ffmpegcolorspace      	  ! \
#      queue                 	  ! \
#      x264enc $X264SETTINGS	  ! \
#      h264parse                   ! \
#      mpegtsmux		  	  ! \
#      tee name=t0                 ! \
#      queue leaky=2           	  ! \
#      filesink location=$file t0. ! \
#      queue 	         	  ! \
#      tcpserversink port=5010
    sleep 2
  fi
done

exit

 shmsrc socket-path=/tmp/mixer1 do-timestamp=true is-live=true ! 'video/x-raw-yuv,width=1024,height=576,format=(fourcc)YUY2,framerate=25/1' ! \
  queue ! ffmpegcolorspace ! x264enc bitrate=3000 tune=zerolatency speed-preset=5 ! h264parse ! tee name=t1 ! \
    rtph264pay ! queue ! udpsink clients=192.168.254.150:5010 sync=false \
    t1. ! queue leaky=2 ! mpegtsmux ! tcpserversink port=5010

