#!/bin/bash

export AUDIOFORMAT='audio/x-raw-int, endianness=(int)1234, signed=(boolean)true, width=(int)16, depth=(int)16, rate=(int)48000, channels=(int)2'
export MIXERFORMAT='video/x-raw-rgb, bpp=(int)32, depth=(int)32, endianness=(int)4321, format=(fourcc)BGRA, red_mask=(int)65280, green_mask=(int)16711680, blue_mask=(int)-16777216, width=(int)1024, height=(int)576, framerate=(fraction)24/1, pixel-aspect-ratio=(fraction)1/1, interlaced=(boolean)false'
export SRC='shmsrc socket-path=/tmp/mixer1 do-timestamp=true is-live=true'
export X264SETTINGS='bitrate=3000 tune=zerolatency speed-preset=5'

DATE=`date '+%y%m%d'`
RECORD=/var/www/recordings/$DATE
DATETIME=$DATE-`date '+%H:%M:%S.%N' | cut -c1-12`
if [ ! -d $RECORD ] ; then
  mkdir $RECORD
  if [ ! -d $RECORD ] ; then
    echo "Failed to create record directory $RECORD" >>$LOGFILE
    exit 1
  fi
fi
RECORDFILE=$RECORD/video-out-$DATETIME


gstreamer_pipelines()
{
  ( echo 'audio sink ctr isaudio 1' ; cat >/dev/null ) | \
    /bin/nc 127.0.0.1 9999	| \
     (head -1
      gst-launch -q -e \
	mpegtsmux name=muxer	! \
	mpegtsparse		! \
	tee name=t1		! \
	queue			! \
	filesink location=$RECORDFILE.ts t1. ! \
	queue 			! \
	tcpserversink port=5010   \
	$SRC			! \
	$MIXERFORMAT		! \
	queue leaky=2		! \
	ffmpegcolorspace	! \
	queue			! \
	x264enc $X264SETTINGS	! \
	'video/x-h264, framerate=(fraction)24/1' ! \
	h264parse		! \
	tee name=t2		! \
	queue			! \
	mpegtsmux 		! \
	mpegtsparse		! \
	queue leaky=2		! \
	tcpserversink port=5020 t2. ! \
	queue			! \
	muxer.			  \
	fdsrc fd=0		! \
	$AUDIOFORMAT		! \
	lamemp3enc		! \
	tee name=t3		! \
	queue leaky=2		! \
	mpegtsmux 		! \
	mpegtsparse		! \
	tcpserversink port=5030 t3. ! \
	queue			! \
	muxer.
      )
}

while true ; do
  snowmix=`ps a |cut -c28-37 | grep snowmix | head -1`
  if [ X$snowmix = X ] ; then
    echo 'Snowmix is not running. Sleeping'
    sleep 2
    continue
  fi
  break
done

gstreamer_pipelines 
