#!/bin/bash

AUDIOFORMAT='audio/x-raw-int, endianness=(int)1234, signed=(boolean)true, width=(int)16, depth=(int)16, rate=(int)44100, channels=(int)1'
MIXERFORMAT='video/x-raw-rgb, bpp=(int)32, depth=(int)32, endianness=(int)4321, format=(fourcc)BGRA, red_mask=(int)65280, green_mask=(int)16711680, blue_mask=(int)-16777216, width=(int)1024, height=(int)576, framerate=(fraction)24/1, pixel-aspect-ratio=(fraction)1/1, interlaced=(boolean)false'
SRC='shmsrc socket-path=/tmp/mixer1 do-timestamp=true is-live=true'

        gst-launch -v -e mpegtsmux name=muxer ! \
		mpegtsparse !\
		 queue ! \
		tcpserversink port=5010 $SRC ! \
		$MIXERFORMAT ! \
		ffmpegcolorspace ! \
		queue ! \
		x264enc $X264SETTINGS ! \
		h264parse ! \
		queue ! \
		muxer.

exit
\
		fdsrc fd=0 ! \
		$AUDIOFORMAT ! \
		audiorate ! \
		lamemp3enc ! \
		queue ! \
		muxer.
        #gst-launch -q -e mpegtsmux name=muxer ! mpegtsparse ! queue ! tcpserversink port=5010 $SRC ! $MIXERFORMAT ! queue leaky=2 ! ffmpegcolorspace ! queue ! x264enc $X264SETTINGS ! h264parse ! queue ! muxer.

