#!/bin/sh
#
# Copyright 2013 by Peter Maersk-Moller. All rights reserved.
#
# This file is intended for testing Snowmix. The setup require
# xinetd to configured with the config files found in xinetd
# of this distribution.

if [ $# -lt 1 ] ; then
  echo "error. usage : $0 <number> [<ip>"
  echo "example : $0 1 127.0.0.1"
  exit 1
fi
if [ $# -lt 2 ] ; then
  IP=127.0.0.1
  #IP=192.168.254.240
  #IP=192.168.2.240
  #IP=193.88.237.22
fi


case $1 in
  1|2|3|5|6|7|8|9)
    stream=$1
    aport=`expr 2 "*" $stream + 9098`
    vport=`expr 2 "*" $stream + 9018`
    channels=1
    ;;
  4)
    stream=$1
    aport=`expr 2 "*" $stream + 9198`
    vport=`expr 2 "*" $stream + 9018`
    channels=2
    ;;
  *) echo "wrong argument. Use 1..9" ; exit 1;;
esac

AUDIOFORMAT='audio/x-raw-int, endianness=(int)1234, signed=(boolean)true, width=(int)16, depth=(int)16, rate=(int)48000, channels=(int)'$channels

while true ; do
	gst-launch -v						  \
		filesrc location=../test/LES_TDS_launch.mp4	! \
		qtdemux name=qtdm0				! \
		queue						! \
		'video/x-h264'					! \
		h264parse					! \
		rtph264pay					! \
		udpsink host=$IP port=$vport sync=true		  \
		qtdm0.						! \
		queue						! \
		'audio/mpeg'					! \
		decodebin2					! \
		audioconvert					! \
		audioresample					! \
		$AUDIOFORMAT					! \
		tcpclientsink host=$IP port=$aport sync=true

	echo 'Clip streamed. Looping.'
	sleep 1
done


