#!/bin/sh
while true ; do
	gst-launch -v filesrc location=../test/LES_TDS_launch.mp4 ! \
		qtdemux name=qtm0		! \
		queue				! \
		'video/x-h264'			! \
		legacyh264parse			! \
		rtph264pay			! \
		'application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264' ! \
		udpsink sockfd=1  | od -c 
exit
\
		gst-launch \
		udpsrc sockfd=0 ! \
		'application/x-rtp, media=(string)video, payload=(int)96, clock-rate=(int)90000, encoding-name=(string)H264' ! \
		rtph264depay			! \
		'video/x-h264'			! \
		ffdec_h264			! \
		ffmpegcolorspace		! \
		ximagesink
	sleep 2
done
exit
		'application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264, sprop-parameter-sets=(string)"Z0LAHtoCgL/lhAAAAwAEAAADAMA8WLqA\,aM48gA\=\=", payload=(int)96, ssrc=(uint)3354181630, clock-base=(uint)84609634, seqnum-base=(uint)13289' ! \
		'application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264, sprop-parameter-sets=(string)\"Z0LAHtoCgL/lhAAAAwAEAAADAMA8WLqA\\,aM48gA\\=\\=\", payload=(int)96, ssrc=(uint)3354181630, clock-base=(uint)84609634, seqnum-base=(uint)13289' ! \
