#!/bin/sh
# \
exec /usr/bin/wish "$0" ${1+"$@"}
#
# !/usr/bin/wish

package require BWidget

. config -bg black
wm geometry . 200x150
#wm minsize . 100 50
wm title . Test

set fr [frame .fr]
pack $fr -side top -fill both
ScrollableFrame $fr.scrollframe -constrainedwidth false -constrainedheight false \
  -xscrollcommand "$fr.scrollbar set" -height 50
scrollbar $fr.scrollbar -command "$fr.scrollframe xview" -orient horizontal
pack $fr.scrollframe -side top
pack $fr.scrollbar -side top -fill x
set holder [$fr.scrollframe getframe]
puts "hold $holder $fr.scrollframe"

Button $holder.button1 -text hello
Button $holder.button2 -text world
Button $holder.button3 -text This
Button $holder.button4 -text is
Button $holder.button5 -text a
Button $holder.button6 -text test
pack $holder.button1 $holder.button2 $holder.button3 $holder.button4 $holder.button5 $holder.button6 -side left -fill x
